<?php

/**
 * Implements hook_menu().
 */
function devel_plus_menu() {
  $items = array();

  $items['devel/plus'] = array(
    'title' => 'Plus',
    'access arguments' => array('access administration pages'),
    'page callback' => 'system_admin_menu_block_page',
    'weight' => 100,
    'file' => 'system.admin.inc',
    'menu_name' => 'devel',
  );

  if (module_exists('advancedqueue')) {
    $items['devel/plus/advancedqueue_queues'] = array(
      'title' => 'Advanced Queue queues',
      'description' => 'View Advanced Queue queue definitions.',
      'page callback' => 'devel_plus_advancedqueue_queues_page',
      'access arguments' => array('access devel information'),
      'file' => 'devel_plus.pages.inc',
      'menu_name' => 'devel',
    );
  }

  $items['devel/plus/cron_queues'] = array(
    'title' => 'Cron queues',
    'description' => 'View cron queue definitions.',
    'page callback' => 'devel_plus_cron_queues_page',
    'access arguments' => array('access devel information'),
    'file' => 'devel_plus.pages.inc',
    'menu_name' => 'devel',
  );

  $items['devel/plus/entity_properties'] = array(
    'title' => 'Entity properties',
    'description' => 'View entity property definitions.',
    'page callback' => 'devel_plus_entity_properties_page',
    'access arguments' => array('access devel information'),
    'file' => 'devel_plus.pages.inc',
    'menu_name' => 'devel',
  );

  $items['devel/plus/permissions'] = array(
    'title' => 'Permissions',
    'description' => 'View permission definitions.',
    'page callback' => 'devel_plus_permission_info_page',
    'access arguments' => array('access devel information'),
    'file' => 'devel_plus.pages.inc',
    'menu_name' => 'devel',
  );

  $items['devel/plus/views_data'] = array(
    'title' => 'Views data',
    'description' => 'View views data definitions.',
    'page callback' => 'devel_plus_views_data_page',
    'access arguments' => array('access devel information'),
    'file' => 'devel_plus.pages.inc',
    'menu_name' => 'devel',
  );

  return $items;
}
